[versions]
dgt = "2.67.0"
kotlin = "2.2.10"
coroutines = "1.10.2"
serialization = "1.9.0"
ktor = "3.3.3"
android = "8.12.0"
outcome = "0.1.0"
compose = "1.9.3"
navigation = "2.9.1"
oshi = "6.6.5"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
outcome = { module = "dev.deftu:outcome", version.ref = "outcome" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
jetbrains-navigation-compose-desktop = { module = "org.jetbrains.androidx.navigation:navigation-compose-desktop", version.ref = "navigation" }
oshi-core = { module = "com.github.oshi:oshi-core", version.ref = "oshi" }

[plugins]
dgt-tools = { id = "dev.deftu.gradle.tools", version.ref = "dgt" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "android" }
android-application = { id = "com.android.application", version.ref = "android" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }

[bundles]
kotlinx-coroutines = ["kotlinx-coroutines-core"]
kotlinx-serialization = ["kotlinx-serialization-json"]
ktor-client = ["ktor-client-core", "ktor-client-websockets", "ktor-client-content-negotiation"]
ktor-serialization = ["ktor-serialization-kotlinx-json"]
ktor-network = ["ktor-network"]
